### ISSUE TITLE
please change the way the Allure TestOps release is being provided

### ISSUE THREAD

**Issue by cheshi-mantu** [qameta/allure-docker-compose#3]
Now, we have the releasse ID defined like this:
![image](https://user-images.githubusercontent.com/8607348/167084615-f87368f0-b7b9-4a65-a500-bf01b6542191.png)

we need to remove the burden from end users' shoulders and move `-compose` part to docker-compose.yml and keep only release ID in .env and in the example file to move it to the top of the file.

i.e. target in .env:
```yaml
export COMPOSE_PROFILES=default,postgres,redis,rabbit,minio-local

ALLURE_VERSION=3.193.1

TZ="Europe/Moscow"
# Standard Login Admin
ALLURE_ADMIN=admin
ALLURE_ADMIN_PASS=admin

```

in the docker-compose.yml

```yaml
  allure-uaa:
    restart: always
    image: ${ALLURE_REGISTRY}/${ALLURE_SLUG}/allure-uaa:${ALLURE_VERSION}-compose

```
